size = WIDTH, HEIGHT = 700, 700
ROAD_WIDTH = 150
WIDTH_CENTRE, HEIGHT_CENTRE = WIDTH/2, HEIGHT/2
ZEBRA_CROSSING_DIST = ROAD_WIDTH/2*1.2
LEFT_ZEBRA_LANE = WIDTH_CENTRE - ZEBRA_CROSSING_DIST
RIGHT_ZEBRA_LANE = WIDTH_CENTRE + ZEBRA_CROSSING_DIST
UP_ZEBRA_LANE = HEIGHT_CENTRE - ZEBRA_CROSSING_DIST
DOWN_ZEBRA_LANE = HEIGHT_CENTRE + ZEBRA_CROSSING_DIST